---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: graph
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: graph-auth
  url: ssh://git@github.com/pokernook/graph
---
apiVersion: v1
data:
  identity: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQkJsMkYzOExXOFBLSTV2Z3AKTVJUR2VGVnByblV4STFHN3RWNGEyR01temE1VFp6eFFMSlVFSzZFVUwvSkhEcHZYSnpXbTBTd3dGQVA1cGxybQorUFFjT1Z1aGdZa0RnWVlBQkFGWGkzNWxWTzNPUWVwU3R5OGtVTXVEYzcwNkl0UVZCZFpWYlFXT1V3djlIcXFBCi8zUWllVGZhMXp4T1VpZTFMRWt6NjlCb2lGQjl6ejA0Qzk0RFptRjZaQUZsaTBnNm4vZXRuZ0taNnhHbFZLVncKNkx1d3RJaDlmbWNuWndyczFvY0gzMkEyTVB2aG55dk5lVG1JVEtDeDU1cDFHbEdIMG9lUkpON2tGSHRIaEpPSQowZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  identity.pub: ZWNkc2Etc2hhMi1uaXN0cDUyMSBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEExTWpFQUFBQUlibWx6ZEhBMU1qRUFBQUNGQkFGWGkzNWxWTzNPUWVwU3R5OGtVTXVEYzcwNkl0UVZCZFpWYlFXT1V3djlIcXFBLzNRaWVUZmExenhPVWllMUxFa3o2OUJvaUZCOXp6MDRDOTREWm1GNlpBRmxpMGc2bi9ldG5nS1o2eEdsVktWdzZMdXd0SWg5Zm1jblp3cnMxb2NIMzJBMk1QdmhueXZOZVRtSVRLQ3g1NXAxR2xHSDBvZVJKTjdrRkh0SGhKT0kwZz09Cg==
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFRRUFxMkE3aFJHbWRubTl0VURiTzlJRFN3Qks2VGJRYStQWFlQQ1B5NnJiVHJUdHc3UEhrY2NLcnBwMHlWaHA1SGRFSWNLcjZwTGxWREJmT0xYOVFVc3lDT1Ywd3pmaklKTmxHRVlzZGxMSml6SGhibjJtVWp2U0FIUXFaRVRZUDgxZUZ6TFFOblBIdDRFVlZVaDdWZkRFU1U4NEtlem1ENVFsV3BYTG12VTMxL3lNZitTZTh4aEhUdktTQ1pJRkltV3dvRzZtYlVvV2Y5bnpwSW9hU2pCK3dlcXFVVW1wYWFhc1hWYWw3MkorVVgyQisyUlBXM1JjVDBlT3pRZ3FsSkwzUktyVEp2ZHNqRTNKRUF2R3EzbEdIU1pYeTI4RzNza3VhMlNtVmkvdzR5Q0U2Z2JPRHFuVFdsZzcrd0M2MDR5ZEdYQThWSmlTNWFwNDNKWGlVRkZBYVE9PQo=
kind: Secret
metadata:
  name: graph-auth
  namespace: flux-system
