---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: graph
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: 0.x # TODO: Should this reference a branch rather than a semver tag?
  url: https://github.com/pokernook/graph
