---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: graph
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux # TODO: Change back to main branch
  url: https://github.com/pokernook/graph
