---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: graph
  namespace: flux-system
spec:
  interval: 30s
  ref:
    semver: 0.x
  url: https://github.com/pokernook/graph
