---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: web
  namespace: flux-system
spec:
  image: ghcr.io/pokernook/web
  interval: 1m0s
  secretRef:
    name: regcred
