---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: graphql
  namespace: flux-system
spec:
  image: ghcr.io/pokernook/graphql
  interval: 10m0s
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: graphql
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: graphql
  policy:
    semver:
      range: 0.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: graphql
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: graphql
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: "[ci skip] update image"
  interval: 10m0s
  update:
    setters: {}
